import Head from 'next/head'
import styles from '../styles/Home.module.scss';
import LandingComponent from '../components/landing/landing';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LandingComponent />
    </div>
  )
}
